template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: incoming_webhook_resource
    type: IncomingWebhook
    configuration:
      webhookName: incoming_webhook

pipelines:
  - name: SamK_RequestsReportPipeline
    steps:
      - name: step1
        type: Bash
        configuration:
          inputResources:
            - name: incoming_webhook_resource
          integrations:
            - name: env_variables_for_usage_pipeline
        execution:
          onStart:
            - ls -ltra
            - echo $UPLOAD_PATH 
            - echo $USER
            - echo $TOKEN
            - echo $REPORT_URL
            - echo $res_incoming_webhook_resource_payload
          onExecute:
            #- docker login -u $USER -p $TOKEN solengcustomersupport.jfrog.io 
            - docker pull skasimalla/generate_report_linux:1
            - docker run --env  "USER=${USER}" --env "TOKEN=${TOKEN}" --env "BASE_URL=${BASE_URL}" --env "JSON=${res_incoming_webhook_resource_payload}" --env "UPLOAD_PATH=${UPLOAD_PATH}" skasimalla/generate_report_linux:1
 
