template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: incoming_webhook_resource
    type: IncomingWebhook
    configuration:
      webhookName: incoming_webhook

pipelines:
  - name: step1
    steps:
      - name: step1_1
        type: Bash
        configuration:
          inputResources:
            - name: incoming_webhook_resource
          integrations:
            - name: env_variables_for_usage_pipeline
        execution:
          onStart:
            - ls -ltra
          onExecute:
            - docker run --env  "USER=${USER}" --env "TOKEN=${TOKEN}" --env "DOWNLOAD_PATH=${DOWNLOAD_PATH}" skasimalla/generate_report_linux:1
 
 
 
  
