template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: incoming_webhook_resource
    type: IncomingWebhook
    configuration:
      webhookName: incoming_webhook

pipelines:
  - name: step1
    steps:
      - name: step1_1
        type: Bash
        configuration:
          inputResources:
            - name: incoming_webhook_resource
          integrations:
            - name: env_variables_for_usage_pipeline
        execution:
          onStart:
            - ls -ltra
          onExecute:
            - echo $res_incoming_webhook_resource_payload
            - docker login -u ${USER} -p ${TOKEN}  solengcustomersupport.jfrog.io
            - docker run --env  "USER=${USER}" --env "TOKEN=${TOKEN}" --env "BASE_URL=${BASE_URL}" --env "JSON=${res_incoming_webhook_resource_payload}" solengcustomersupport.jfrog.io/docker-local/generate_report_linux:1
 
