template: true   # required for local templates
valuesFilePath: ./values.yml

pipelines:

  - name: step1
    steps:
      - name: step1_1
        type: Bash
        configuration:
          integrations:
            - name: env_variables_for_usage_pipeline
        execution:
          onStart:
            - ls -ltra
          onExecute:
            - docker run --env  "USER=${USER}" --env "TOKEN=${TOKEN}" --env "DOWNLOAD_PATH=${DOWNLOAD_PATH}" skasimalla/generate_report:1
 
 
 
  
